config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/login' => 'session#login'
  post '/login' => 'session#process_login_praktikan'
  get '/logout' => 'session#logout'
  get '/admin/login' => 'session#admin'
  post '/admin/login' => 'session#process_login_admin'
  get '/403' => 'session#page403'
  get '/MyProject' => 'projects#indexStudent'

  resources 'practicums'
  resources 'students'
  resources 'projects'
  resources 'users'
  resources 'responsibles'

end

app/models/student.rb
class Student < ActiveRecord::Base
  before_create :ecrypt_password
  validates :npm, :name, :class_name, :gender, :address, presence: true

  def self.authenticate(npm, password)
    student = Student.where(npm: npm).first
    if student && student.password_hash == BCrypt::Engine.hash_secret(password, student.password_salt)
      student
    end
  end

  private

  def ecrypt_password
    self.role = 'ROLE_MAHASISWA'
    self.enable = true
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password_hash, password_salt)
  end

  has_many :projects
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    if session[:user_role]
      if session[:user_role] == 'ROLE_ADMIN'
        @students = Student.paginate(page: params[:page], per_page: 5)
      else
        redirect_to '/403'
      end
    else
      redirect_to '/login'
    end
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.valid?
      @student.save
      if session[:user_role]
        flash[:notice] = 'anda berhasil membuat data mahasiswa'
        redirect_to '/'
      else
        flash[:notice] = 'anda berhasil melakukan register, silahkan login'
        redirect_to '/login'
      end
    else
      render 'new'
    end
  end

  def edit
    if session[:user_role]
      if session[:user_role] == 'ROLE_ADMIN'
        @student = Student.find(params[:id])
      else
        redirect_to '/403'
      end
    else
      redirect_to '/login'
    end
  end

  def editBiodata
    if session[:user_role]
      if session[:user_role] == 'ROLE_MAHASISWA'
        @student = Student.find(session[:user_role])
      else
        redirect_to '/403'
      end
    else
      redirect_to '/login'
    end
  end

  def update
    if session[:user_role]
      if session[:user_role] == 'ROLE_ADMIN'
        @student = Student.find(params[:id])
        if @student.update(student_params)
          flash[:notice] = 'data mahasiswa berhasil diubah'
          redirect_to students_path
        else
          render 'edit'
        end
      elsif session[:user_role] == 'ROLE_MAHASISWA'
        @student = Student.find(params[:id])
        if @student.update(student_params)
          flash[:notice] = 'anda berhasil mengubah biodata anda'
          redirect_to '/'
        else
          render 'editBiodata'
        end
      else
        redirect_to '/403'
      end
    else
      redirect_to '/login'
    end
  end

  def destroy
    if session[:user_role]
      if session[:user_role] == 'ROLE_ADMIN'
        @student = Student.find(params[:id])
        @student.destroy
        redirect_to students_path
      else
        redirect_to '/403'
      end
    else
      redirect_to '/login'
    end
  end

  private

  def student_params
    params.require(:student).permit(:npm, :name, :class_name, :gender, :address, :password_hash)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for @student, :html => { :class => "form-horizontal student" } do |f| %>

<% if @student.errors.any? %>
<div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@student.errors.count, "error") %>
            prohibited this student from being saved:</h3>
    </div>
    <div class="panel-body">
        <ul>
            <% @student.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
</div>
<% end %>

<% if @student.npm %>
<div class="form-group">
    <%= f.label :npm, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
        <%= f.text_field :npm, :class => 'form-control', :disabled => true %>
    </div>
    <%=f.error_span(:npm) %>
</div>
<% else %>
<div class="form-group">
    <%= f.label :npm, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
        <%= f.text_field :npm, :class => 'form-control' %>
    </div>
    <%=f.error_span(:npm) %>
</div>
<% end %>

<div class="form-group">
    <%= f.label :nama, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
        <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
</div>

<div class="form-group">
    <%= f.label :password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
        <%= f.password_field :password_hash, :class => 'form-control' %>
    </div>
    <%=f.error_span(:password_hash) %>
</div>

<div class="form-group">
    <%= f.label :kelas, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
        <%= f.text_field :class_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:class_name) %>
</div>
<div class="form-group">
    <%= f.label :jenis_kelamin, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
        <%= f.text_field :gender, :class => 'form-control' %>
    </div>
    <%=f.error_span(:gender) %>
</div>
<div class="form-group">
    <%= f.label :alamat, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
        <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address) %>
</div>

<div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">

        <% if @student.npm %>
        <%= f.submit :update, :class => 'btn btn-update' %>
    <% else %>
        <%= f.submit :simpan, :class => 'btn btn-primary' %>
        <% end %>

        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                students_path, :class => 'btn btn-default' %>
    </div>
</div>

<% end %>

app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
    <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/editBiodata.html.erb
<%- model_class = Student -%>
<div class="page-header">
    <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/index.html.erb
<%- model_class = Student -%>
<div class="page-header">
    <h1>Data Mahasiswa</h1>
</div>
<%= link_to t('.new', :default => t("helpers.links.Tambah")),
            new_student_path,
            :class => 'btn btn-primary' %>
<table class="table table-striped table-bordered table-responsive table-hover">
    <thead>
        <tr>
            <th class="text-center"><%= model_class.human_attribute_name(:npm) %></th>
            <th class="text-center"><%= model_class.human_attribute_name(:nama) %></th>
            <th class="text-center"><%= model_class.human_attribute_name(:kelas) %></th>
            <th class="text-center"><%= model_class.human_attribute_name(:jenis_kelamin) %></th>
            <th class="text-center"><%= model_class.human_attribute_name(:alamat) %></th>
            <th class="text-center"><%=t '.actions', :default => t("helpers.Aksi") %></th>
        </tr>
    </thead>
    <tbody>
        <% @students.each do |student| %>
        <tr>
            <td><%= student.npm %></td>
            <td><%= student.name %></td>
            <td><%= student.class_name %></td>
            <td><%= student.gender %></td>
            <td><%= student.address %></td>
            <td class="text-center">
                <%= link_to t('.edit', :default => t("helpers.links.Edit")),
                      edit_student_path(student), :class => 'btn btn-success' %>
                <%= link_to t('.destroy', :default => t("helpers.links.Hapus")), student_path(student), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Apakah anda ingin menghapus data ?')) }, :class =>
                'btn btn-danger' %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>

app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
    <h1>Register</h1>
</div>
<%= render :partial => 'form' %>