config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/login' => 'session#login'
  post '/login' => 'session#process_login_praktikan'
  get '/logout' => 'session#logout'
  get '/admin/login' => 'session#admin'
  post '/admin/login' => 'session#process_login_admin'
  get '/403' => 'session#page403'
  get '/MyProject' => 'projects#indexStudent'

  resources 'practicums'
  resources 'students'
  resources 'projects'
  resources 'users'
  resources 'responsibles'

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name_project, :name_file, presence: true

  belongs_to :practicum
  belongs_to :student
  belongs_to :responsible
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.select('practicums.*, projects.*, students.*, students.name as student_name, responsibles.*')
                       .joins('INNER JOIN practicums
                               ON practicums.id_practicum = projects.practicum_id_practicum
                               INNER JOIN students
                               ON students.npm = projects.student_npm
                               INNER JOIN responsibles
                               ON responsibles.id_assistant = projects.responsibles_id_assistant')
                       .paginate(page: params[:page], per_page: 5)
  end

  def indexStudent
    if session[:user_role]
      if session[:user_role] == 'ROLE_MAHASISWA'
        @projects = Project.select('practicums.*, projects.*, students.*, responsibles.*')
                           .joins('INNER JOIN practicums
                                   ON practicums.id_practicum = projects.practicum_id_practicum
                                   INNER JOIN students
                                   ON students.npm = projects.student_npm
                                   INNER JOIN responsibles
                                   ON responsibles.id_assistant = projects.responsibles_id_assistant')
                           .where(student_npm: session[:user_npm])
                           .paginate(page: params[:page], per_page: 5)
      else
        redirect_to '/403'
      end
    else
      redirect_to '/login'
    end
  end

  def new
    @project = Project.new
  end

  def create
    if session[:user_role]
      if session[:user_role] == 'ROLE_MAHASISWA'
        name_file = params[:project][:name_file]

        file_extension = File.extname(name_file.original_filename)
        new_file_name = SecureRandom.uuid

        File.open(Rails.root.join('public', 'uploads', "#{new_file_name}#{file_extension}"), 'wb') do |file|
          file.write name_file.read
        end

        @project = Project.new(project_params)
        @project.id_project = SecureRandom.uuid
        @project.name_file = "#{new_file_name}#{file_extension}"
        @project.student_npm = session[:user_npm]
        if @project.valid?
          @project.save
          flash[:notice] = 'data project berhasil disimpan'
          redirect_to projects_path
        else
          render 'new'
        end
      else
        redirect_to '/403'
      end
    else
      redirect_to '/login'
    end
  end

  def edit
    if session[:user_role]
      if session[:user_role] == 'ROLE_MAHASISWA'
        @project = Project.find(params[:id])
      else
        redirect_to '/403'
      end
    else
      redirect_to '/login'
    end
  end

  def update
    if session[:user_role]
      if session[:user_role] == 'ROLE_MAHASISWA'
        @project = Project.find(params[:id])

        if @project.update(project_params)
          redirect_to projects_path
        else
          render 'edit'
        end
      else
        redirect_to '/403'
      end
    else
      redirect_to '/login'
    end
  end

  def destroy
    if session[:user_role]
      if session[:user_role] == 'ROLE_MAHASISWA'
        @project = Project.find(params[:id])
        @project.destroy
        redirect_to projects_path
      else
        redirect_to '/403'
      end
    else
      redirect_to '/login'
    end
  end

  private

  def project_params
    params.require(:project).permit(:name_project, :name_file, :practicum_id_practicum, :responsibles_id_assistant)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => "form-horizontal project" } do |f| %>

<% if @project.errors.any? %>
<div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@project.errors.count, "error") %>
            prohibited this project from being saved:</h3>
    </div>
    <div class="panel-body">
        <ul>
            <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
</div>
<% end %>

<% if @project.id_project %>
<div class="form-group">
    <%= f.label :id_project, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
        <%= f.text_field :id_project, :class => 'form-control', :disabled => true %>
    </div>
    <%=f.error_span(:id_project) %>
</div>
<% end %>

<div class="form-group">
    <%= f.label :nama_project, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
        <%= f.text_field :name_project, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name_project) %>
</div>

<div class="form-group">
    <%= f.label :penanggung_jawab, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
        <%= f.collection_select :responsibles_id_assistant, Responsible.all, :id, :name, {prompt: "Pilih Penanggung Jawab"}, {class: "form-control"} %>
    </div>
    <%=f.error_span(:responsibles_id_assistant) %>
</div>

<div class="form-group">
    <%= f.label :file, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
        <%= f.file_field :name_file, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name_file) %>
</div>

<div class="form-group">
    <%= f.label :praktikum, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
        <%= f.collection_select :practicum_id_practicum, Practicum.all, :id, :practicum_name, {prompt: "Pilih Praktikum"}, {class: "form-control"} %>
    </div>
    <%=f.error_span(:practicum_id_practicum) %>
</div>

<div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
        <% if @project.id_project %>
        <%= f.submit :update, :class => 'btn btn-success' %>
    <% else %>
        <%= f.submit :simpan, :class => 'btn btn-primary' %>
        <% end %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn btn-default' %>
    </div>
</div>

<% end %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
    <h1>Edit Project</h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
    <h1>Data Project</h1>
</div>

<% if session[:user_role] == 'ROLE_ADMIN' %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>
<% end %>

<table class="table table-striped table-bordered table-responsive table-hover">
    <thead>
        <tr>
            <th class="text-center"><%= model_class.human_attribute_name(:id_project) %></th>
            <th class="text-center"><%= model_class.human_attribute_name(:nama) %></th>
            <th class="text-center"><%= model_class.human_attribute_name(:nama_project) %></th>
            <th class="text-center"><%= model_class.human_attribute_name(:nama_file) %></th>
            <th class="text-center"><%= model_class.human_attribute_name(:penanggung_jawab) %></th>
            <th class="text-center"><%= model_class.human_attribute_name(:Praktikum) %></th>
            <% if session[:user_role] == 'ROLE_ADMIN' %>
            <th class="text-center"><%=t '.actions', :default => t("helpers.Aksi") %></th>
            <% end %>
        </tr>
    </thead>
    <tbody>
        <% @projects.each do |project| %>
        <tr>
            <td><%= project.id_project %></td>
            <td><%= project.student_name %></td>
            <td><%= project.name_project %></td>
            <td><%= project.name_file %></td>
            <td><%= project.name %></td>
            <td><%= project.practicum_name %></td>
            <% if session[:user_role] == 'ROLE_ADMIN' %>
            <td class="text-center">
                <%= link_to t('.edit', :default => t("helpers.links.Edit")),
                      edit_project_path(project), :class => 'btn btn-success' %>
                <%= link_to t('.destroy', :default => t("helpers.links.Hapus")), project_path(project), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Anda ingin menghapus data ?')) }, :class => 'btn
                btn-danger' %>
            </td>
            <% end %>
        </tr>
        <% end %>
    </tbody>
</table>

<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>

app/views/projects/indexStudent.html.erb
<%- model_class = Project -%>
<div class="page-header">
    <h1>Data Project Pribadi</h1>
</div>

<%= link_to t('.new', :default => t("helpers.links.Tambah")),
            new_project_path,
            :class => 'btn btn-primary' %>

<table class="table table-striped table-bordered table-responsive table-hover">
    <thead>
        <tr>
            <th class="text-center"><%= model_class.human_attribute_name(:id_project) %></th>
            <th class="text-center"><%= model_class.human_attribute_name(:nama_project) %></th>
            <th class="text-center"><%= model_class.human_attribute_name(:nama_file) %></th>
            <th class="text-center"><%= model_class.human_attribute_name(:penanggung_jawab) %></th>
            <th class="text-center"><%= model_class.human_attribute_name(:Praktikum) %></th>
            <th class="text-center"><%=t '.actions', :default => t("helpers.Aksi") %></th>
        </tr>
    </thead>
    <tbody>
        <% @projects.each do |project| %>
        <tr>
            <td><%= project.id_project %></td>
            <td><%= project.name_project %></td>
            <td><%= project.name_file %></td>
            <td><%= project.name %></td>
            <td><%= project.practicum_name %></td>
            <td class="text-center">
                <%= link_to t('.edit', :default => t("helpers.links.Edit")),
                      edit_project_path(project), :class => 'btn btn-success' %>
                <%= link_to t('.destroy', :default => t("helpers.links.Hapus")), project_path(project), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Anda ingin menghapus data ?')) }, :class => 'btn
                btn-danger' %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
    <h1>Tambah Project</h1>
</div>
<%= render :partial => 'form' %>