config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/login' => 'session#login'
  post '/login' => 'session#process_login_praktikan'
  get '/logout' => 'session#logout'
  get '/admin/login' => 'session#admin'
  post '/admin/login' => 'session#process_login_admin'
  get '/403' => 'session#page403'
  get '/MyProject' => 'projects#indexStudent'

  resources 'practicums'
  resources 'students'
  resources 'projects'
  resources 'users'
  resources 'responsibles'

end

app/models/responsible.rb
class Responsible < ActiveRecord::Base
  validates :name, :phone, presence: true

  has_many :projects
end

app/controllers/responsibles_controller.rb
class ResponsiblesController < ApplicationController
  def index
    if session[:user_role]
      if session[:user_role] == 'ROLE_ADMIN'
        @responsibles = Responsible.paginate(page: params[:page], per_page: 5)
      else
        redirect_to '/403'
      end
    else
      redirect_to '/login'
    end
  end

  def new
    if session[:user_role]
      if session[:user_role] == 'ROLE_ADMIN'
        @responsible = Responsible.new
      else
        redirect_to '/403'
      end
    else
      redirect_to '/login'
    end
  end

  def create
    if session[:user_role]
      if session[:user_role] == 'ROLE_ADMIN'
        @responsible = Responsible.new(responsible_params)
        @responsible.id_assistant = SecureRandom.uuid
        if @responsible.valid?
          @responsible.save
          flash[:notice] = 'data asisten tersimpan'
          redirect_to responsibles_path
        else
          render 'new'
        end
      else
        redirect_to '/403'
      end
    else
      redirect_to '/login'
    end
  end

  def edit
    if session[:user_role]
      if session[:user_role] == 'ROLE_ADMIN'
        @responsible = Responsible.find(params[:id])
      else
        redirect_to '/403'
      end
    else
      redirect_to '/login'
    end
  end

  def update
    if session[:user_role]
      if session[:user_role] == 'ROLE_ADMIN'
        @responsible = Responsible.find(params[:id])
        if @responsible.update(responsible_params)
          flash[:notice] = 'data asisten berhasil diubah'
          redirect_to responsibles_path
        else
          render 'edit'
        end
      else
        redirect_to '/403'
      end
    else
      redirect_to '/login'
    end
  end

  def destroy
    if session[:user_role]
      if session[:user_role] == 'ROLE_ADMIN'
        @responsible = Responsible.find(params[:id])
        @responsible.destroy
        redirect_to responsibles_path
      else
        redirect_to '/403'
      end
    else
      redirect_to '/login'
    end
  end

  private

  def responsible_params
    params.require(:responsible).permit(:name, :phone)
  end
end

app/helpers/responsibles_helper.rb
module ResponsiblesHelper
end

app/views/responsibles/_form.html.erb
<%= form_for @responsible, :html => { :class => "form-horizontal responsible" } do |f| %>

<% if @responsible.errors.any? %>
<div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@responsible.errors.count, "error") %>
            prohibited this responsible from being saved:</h3>
    </div>
    <div class="panel-body">
        <ul>
            <% @responsible.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
</div>
<% end %>

<% if @responsible.id_assistant %>
<div class="form-group">
    <%= f.label :id_asisten, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
        <%= f.text_field :id_assistant, :class => 'form-control', :disabled => true %>
    </div>
    <%=f.error_span(:id_assistant) %>
</div>
<% end %>

<div class="form-group">
    <%= f.label :nama, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
        <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
</div>
<div class="form-group">
    <%= f.label :no_telpon, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
        <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phone) %>
</div>

<div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
        <% if @responsible.id_assistant %>
        <%= f.submit :update, :class => 'btn btn-success' %>
    <% else %>
        <%= f.submit :simpan, :class => 'btn btn-primary' %>
        <% end %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                responsibles_path, :class => 'btn btn-default' %>
    </div>
</div>

<% end %>

app/views/responsibles/edit.html.erb
<%- model_class = Responsible -%>
<div class="page-header">
    <h1>Edit Asisten</h1>
</div>
<%= render :partial => 'form' %>

app/views/responsibles/index.html.erb
<%- model_class = Responsible -%>
<div class="page-header">
    <h1>Data Asisten</h1>
</div>
<%= link_to t('.new', :default => t("helpers.links.Tambah")),
            new_responsible_path,
            :class => 'btn btn-primary' %>
<table class="table table-striped table-bordered table-responsive table-hover">
    <thead>
        <tr>
            <th class="text-center"><%= model_class.human_attribute_name(:id_asisten) %></th>
            <th class="text-center"><%= model_class.human_attribute_name(:nama) %></th>
            <th class="text-center"><%= model_class.human_attribute_name(:no_telpon) %></th>
            <th class="text-center"><%=t '.actions', :default => t("helpers.Aksi") %></th>
        </tr>
    </thead>
    <tbody>
        <% @responsibles.each do |responsible| %>
        <tr>
            <td><%= responsible.id_assistant %></td>
            <td><%= responsible.name %></td>
            <td><%= responsible.phone %></td>
            <td class="text-center">
                <%= link_to t('.edit', :default => t("helpers.links.Edit")),
                      edit_responsible_path(responsible), :class => 'btn btn-success' %>
                <%= link_to t('.destroy', :default => t("helpers.links.Hapus")), responsible_path(responsible), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Anda ingin menghapus data ?')) }, :class =>
                'btn btn-danger' %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/responsibles/new.html.erb
<%- model_class = Responsible -%>
<div class="page-header">
    <h1>Tambah Asisten</h1>
</div>
<%= render :partial => 'form' %>