config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/login' => 'session#login'
  post '/login' => 'session#process_login_praktikan'
  get '/logout' => 'session#logout'
  get '/admin/login' => 'session#admin'
  post '/admin/login' => 'session#process_login_admin'
  get '/403' => 'session#page403'
  get '/MyProject' => 'projects#indexStudent'

  resources 'practicums'
  resources 'students'
  resources 'projects'
  resources 'users'
  resources 'responsibles'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><%= content_for?(:title) ? yield(:title) : "Project Labti" %></title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag "application", :media => "all" %>

        <!-- For third-generation iPad with high-resolution Retina display: -->
        <!-- Size should be 144 x 144 pixels -->
        <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

        <!-- For iPhone with high-resolution Retina display: -->
        <!-- Size should be 114 x 114 pixels -->
        <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

        <!-- For first- and second-generation iPad: -->
        <!-- Size should be 72 x 72 pixels -->
        <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

        <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
        <!-- Size should be 57 x 57 pixels -->
        <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

        <!-- For all other devices -->
        <!-- Size should be 32 x 32 pixels -->
        <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

        <%= javascript_include_tag "application" %>

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]> <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script> <![endif]-->
    </head>
    <body>

        <div class="navbar navbar-default navbar-static-top">
            <div class="container">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Project Labti</a>
                <div class="navbar-collapse collapse navbar-responsive-collapse">
                    <ul class="nav navbar-nav">
                        <% if session[:user_role] == 'ROLE_ADMIN' %>
                        <li><%= link_to "Data Praktikum", practicums_path  %></li>
                        <li><%= link_to "Data Mahasiswa", students_path  %></li>
                        <li><%= link_to "Data User", users_path %></li>
                        <% end %>
                        <% if session[:user_role] == 'ROLE_MAHASISWA' %>
                        <li><%= link_to "Data Project Pribadi", '/MyProject' %></li>
                        <% end %>
                        <% if !session[:user_role] %>
                        <li><%= link_to "Register", new_student_path %></li>
                        <li><%= link_to "Login", '/login'  %></li>
                        <% end %>
                        <li><%= link_to "Data Project", projects_path %></li>
                        <li><%= link_to "Data Asisten", responsibles_path %></li>
                    </ul>
                    <% if session[:user_role] %>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                Selamat Datang
                                <%= session[:user_name] %>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="/logout">Logout</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <% end %>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <%= bootstrap_flash %>
                <%= yield %>
            </div>
            <!--/row-->

            <footer>
                <p>&copy; Laboratorium Teknik Informatika 2016, Rizki Mufrizal</p>
            </footer>

        </div>
        <!-- /container -->

    </body>
</html>